export const SET_LOADING_ARTICLES = 'SET_LOADING_ARTICLES';
export const SET_LOADING_TAGS = 'SET_LOADING_TAGS';
export const SET_LIMIT = 'SET_LIMIT';
export const SET_SHOWPASSWORD = 'SET_SHOWPASSWORD';
